build:
	gcc oets.c -o oets -lpthread -lm -Wall
	gcc shear.c -o shear -lpthread -lm -Wall
	gcc merge.c -o merge -lpthread -lm -Wall
	gcc oets_sec.c -o oets_sec -lpthread -lm -Wall
	gcc shear_sec.c -o shear_sec -lpthread -lm -Wall

clean:
	rm -rf oets shear merge oets_sec shear_sec
